// Generated by ReScript, PLEASE EDIT WITH CARE


var Scripts = {};

var Links = {};

var LiveReload = {};

var Meta = {};

var Outlet = {};

export {
  Scripts ,
  Links ,
  LiveReload ,
  Meta ,
  Outlet ,
}
/* No side effect */
