// Generated by ReScript, PLEASE EDIT WITH CARE

import PicoCss from "../src/pico.css";
import * as React from "@remix-run/react";
import * as JsxRuntime from "react/jsx-runtime";

var styles = PicoCss;

function links() {
  return [{
            rel: "stylesheet",
            href: styles
          }];
}

function meta() {
  return [
          {
            name: "viewport",
            content: "width=device-width, initial-scale=1"
          },
          {
            title: "The Josh Derocher"
          }
        ];
}

function Root(props) {
  return JsxRuntime.jsxs("html", {
              children: [
                JsxRuntime.jsxs("head", {
                      children: [
                        JsxRuntime.jsx("link", {
                              href: "data:image/x-icon;base64,AA",
                              rel: "icon"
                            }),
                        JsxRuntime.jsx(React.Meta, {}),
                        JsxRuntime.jsx(React.Links, {})
                      ]
                    }),
                JsxRuntime.jsxs("body", {
                      children: [
                        JsxRuntime.jsx("main", {
                              children: JsxRuntime.jsx(React.Outlet, {})
                            }),
                        JsxRuntime.jsx(React.Scripts, {}),
                        JsxRuntime.jsx(React.LiveReload, {})
                      ]
                    })
              ],
              lang: "en"
            });
}

var make = Root;

var $$default = Root;

export {
  styles ,
  links ,
  meta ,
  make ,
  $$default as default,
}
/* styles Not a pure module */
