// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Foo$dot_index(props) {
  return JsxRuntime.jsx("p", {
              children: "foo bar"
            });
}

var make = Foo$dot_index;

var $$default = Foo$dot_index;

export {
  make ,
  $$default as default,
}
/* react/jsx-runtime Not a pure module */
