// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime"

function Component(props) {
	return JsxRuntime.jsx("h2", {
		children: "Hello world!",
	})
}

var make = Component

export { make }
/* react/jsx-runtime Not a pure module */
