// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Home_hero(props) {
  return JsxRuntime.jsx("h1", {
              children: "Hello world?"
            });
}

var make = Home_hero;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
